name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: dotnet restore
        run: dotnet restore

      - name: dotnet build
        run: dotnet build --no-restore -c Release

      - name: dotnet test
        run: dotnet test --no-build -c Release

      - name: dotnet pack
        run: dotnet pack --no-build -c Release --include-source --include-symbols -p:PackageVersion='${{ env.CI_REF_NAME }}' -p:SymbolPackageFormat=snupkg
